# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [3]:
np.zeros產生陣列中的每一項都是0。
np.empty產生陣列的每一項是0或接近0的極小數值。

'\nYour Code\n'

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [6]:
# 參考解答

a = np.random.rand(2, 3)
b = np.array(a, dtype = int)
c = a.round()
print(a)
print(b)
print(c)

[[0.42140865 0.85306903 0.54248881]
 [0.91004422 0.72024801 0.62710177]]
[[0 0 0]
 [0 0 0]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [8]:
m = 20
n = 40

from numpy.random import default_rng
rng = default_rng()

c = rng.integers(m, n, size = (2,3))
print(c)

[[35 36 28]
 [27 20 20]]
